### ISSUE TITLE
is this still in development?

### ISSUE THREAD

**Issue by cytec** [danesparza/tvdb#1]
seems like there is missing a huge part as far as i can tell it only lets you search the api for a show and query it for episodes.

what about actors, images and the updates endpoint? any plans on adding those?

**Comment by danesparza** [comment]
Hey @cytec -- no active plans.  But I'll accept pull requests.  :smile: 

If you had to pick, which one of the items you mentioned is highest priority?  If I have some free time this week I'll work on it.

**Comment by cytec** [comment]
I've opened a PR for the updated endpoint... just a few thoughts while coding it:

* seems like there is a huge bunch of duplicate code in there not really sure what's the best way to fix this (might somehow put request handling to a intern function like: sendRequest(method, url) which returns the response and also put Headers.Set in there as that simple is exactly the same for each request
* the client might should have an option for the accepted language as well

**Comment by danesparza** [comment]
I like your suggestion to remove duplicate code.  I'll work on that next.

**Comment by danesparza** [comment]
@cytec I have created a two helper methods:  one to initialize the client (which I might move to a 'New' method) and one to make the API call.  Let me know what you think.

**Comment by cytec** [comment]
@danesparza just scrolled through the code quickly looks pretty good to me. Nice work! i have one more thing you might want to consider: 

currently `makeAPIcall` makes a get request, for further development one need to make PUT, DELETE and POST requests as well (if i remember that correctly) i'd just ad a "method" (string) argument which then uses a case switch to consider if `http.Post`, `http.Get` etc should be used, and may add an extra interface as well for the payload to send in POST, PUT requests.

Then the `makeAPIcall` function could also be used for `Login` (given that you'll change `initialize` to check/set the URI before calling `Login`

Not that  important but might shuld be considered, that's all popping up my head right now, might get a closer look tomorrow :)
